version: "3.9"
services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  app:
    build: .
    environment:
      MONGODB_URI: mongodb://mongo:27017/btg
      JWT_SECRET: S3cUr3-JWT-K3y-For-D3v-T3sts-1234567890!
    ports:
      - "8080:8080"
    depends_on:
      - mongo
volumes:
  mongo_data: {}